# Generated by Django 3.2.5 on 2022-04-30 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='书名')),
                ('pub_date', models.DateField(null=True)),
                ('read_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '书籍名',
                'db_table': 'bookinfo',
            },
        ),
        migrations.CreateModel(
            name='PeopleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'unknown')], default=2, verbose_name='性别')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='描述')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookinfo', verbose_name='对应书名')),
            ],
            options={
                'verbose_name': '人物信息',
                'db_table': 'peopleinfo',
            },
        ),
    ]
